# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/search_constr.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_2 || ORIG_REF_NAME==design_1_processing_system7_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sentinel_search_ip_0_3/design_1_sentinel_search_ip_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sentinel_search_ip_0_3 || ORIG_REF_NAME==design_1_sentinel_search_ip_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_intc_0_1/design_1_axi_intc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_intc_0_1 || ORIG_REF_NAME==design_1_axi_intc_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_2/design_1_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_2 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_2} -quiet] -quiet

# XDC: /home/rickg/Desktop/NoSync/AXISearch/sentinel_value/sentinel_value.gen/sources_1/bd/design_1/design_1_ooc.xdc
